/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "xb-blog",
  "description": "My Blog",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/logo.jpg"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3b551d9c",
      "path": "/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "我的GitHub",
        "link": "https://github.com/xianbo-deep"
      }
    ],
    "sidebar": "auto",
    "sidebarDepth": 2
  }
}